### ISSUE TITLE
Responsinator can't create a ExpandoObject from a ExpandoObject

### ISSUE THREAD

**Issue by josellm** [AnthonyCarl/ServiceStack.PartialResponse#1]
iIf the object is a ExpandoObject just not work

**Comment by AnthonyCarl** [comment]
I should be able to update the `TraverseSingleObject` method in the `PartialResponsinator` class to properly handle `ExpandoObject`.

**Comment by AnthonyCarl** [comment]
I added support for Dynamic Objects. You can download the NuGet package files directly from the build server. If possible, please check it out and let me know if it works. If everything looks good I will push to Nuget.org.

http://teamcity.codebetter.com/viewType.html?buildTypeId=bt1037
